"""empty message

Revision ID: 691099422aae
Revises: e85beebcc102
Create Date: 2024-06-04 21:10:04.317686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691099422aae'
down_revision = 'e85beebcc102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
